### ISSUE TITLE
Epic: Add capability to execute zarf commands with the action

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/setup-zarf#35]
Currently, the setup-zarf action downloads the zarf binary and zarf init package, and does the necessary things to allow them to work together (i.e. execute `zarf init` to initialize a zarf-managed cluster).

Feedback from interested, potential users of this GitHub action have stated the desire to have the GitHub action do more than this.

In particular, the capabilities we are looking to add right now are as follows:

- [ ] Log in to [registry1.dso.mil](http://registry1.dso.mil/) (zarf tools registry login)

- [ ] Package (zarf package create)

- [ ] Deploy (zarf package init / zarf package deploy)

GitHub provides an [actions library](https://github.com/actions/toolkit/tree/main/packages/exec) for executing CLI tools in a cross-platform way that will likely be helpful in providing this functionality.

This work would likely benefit from focusing on adding one capability at a time, so these will be split out into issues of their own as well.

Some things to keep in mind for this work:
- Determine the behavior we expect of the logic we are adding
- Before writing any code, write a test for that desired/expected behavior, and intentionally write it so that it will fail
- Fix the test to where it is passing now
- Write the logic you need
- Rinse and repeat

**Comment by jeff-mccoy** [comment]
This is not a standard behavior for github actions. We should avoid doing any special sauce here. GH actions should install the tool and leave it up to the devs to use it.  The exception might be a docker login, but there's already a very well-established action everyone uses for that and not everyone will need to login to a registry.

**Comment by lucasrod16** [comment]
This action has undergone a refactor, which involved the decision to limit the scope of this action to only downloading the zarf binary and an init package, so this work is not needed anymore.

See this [PR](https://github.com/defenseunicorns/setup-zarf/pull/42) for more information
